### PR TITLE
Add reverse-proxy with CORS Access-Control-Allow-Origin for PlutoTV

### PR DESCRIPTION
**Pull request by ProteanCoding**
To be used with
`VideoPlayer.create(entity, { src: 'http://localhost/plutotv/v1/stitch/...' })`
in order to reach
`https://stitcher-ipv4.pluto.tv/v1/stitch/...`

### CODE REVIEW

**Comment by menduz** [comment]
Hi thanks for posting, sadly this modification involves a third party service that may compromise the catalysts, consuming their bandwidth and acting to serve illegal content in many jurisdictions. As a rule of thumb, catalysts should not add any new proxy to external providers

**Comment by ProteanCoding** [comment]
Hi ! You're welcome.
There is no extra 3rd-party service being used (`nginx` is already active).
PlutoTV's content is already freely available. The streaming already works in the Desktop App !
All this change does is to assuage a serving browser that there is no malicious CORS issue with this specific connection, preventing the dreaded `CORS header does not match` rejection.

**Comment by menduz** [comment]
I'd suggest to find a solution that doesn't involve adding an unmeasured-bandwidth requirement to catalysts. Those servers are run by the community and so far, those are not proxying any external service to serve content to the scenes. You can, though, add this to your own catalyst, as a custom configuration. But we should gate-keep a sane set of default configurations in this repository.

You could use other free services like corsproxy dot io, crossorigin dot me or even deploy a free custom cloudflare worker for this task

**Comment by ProteanCoding** [comment]
Right, I didn't consider how the stream won't actually stay on only one server that way when in production.

I tried using free proxy services, but they have limits on bandwidth consumption.

I suspect a free custom cloudflare worker would also not work, the free plan on https://developers.cloudflare.com/workers/platform/pricing/ lists `10 milliseconds of CPU time per invocation`.

Just to make sure, there isn't any documentation already on how to achieve this in a DCL scene, right ?

**Comment by menduz** [comment]
In cloudflare, they only charge you the time of CPU, not the proxy-ed request. If that were the case, no CDN would be feasible using workers, and there are plenty. cdn.decentraland.org being one off them

**Comment by ProteanCoding** [comment]
Thanks for your guidance ! I was able to get the proxy running on Heroku ⁀‿⁀

**Pull request closed without merging**
