### PR TITLE
merge Development to master

### PR DESCRIPTION
**Pull request by agusaldasoro**

### CODE REVIEW

**Review by nchamo — APPROVED** [review]

**Review by menduz — CHANGES_REQUESTED** [review]
The intended usage of that header expects a host domain, without protocol and path ("/content"). What is the intention of this change?

**Comment by agusaldasoro** [comment]
> The intended usage of that header expects a host domain, without protocol and path ("/content"). What is the intention of this change?

In the Catalyst we need to create the URL link to the next item in the collection: https://github.com/decentraland/catalyst/pull/442/files#diff-a81f9626fbdc82c0679e13f0cfae2d1999ed00b6aae0d2df165251f02f0931e9R132

The problem there is that the service itself doesn't know that it's behind the path `/lambdas`, this is something of the nginx configuration. Indeed, the base url that has the request inside the catalyst doesn't contain the `/lambdas` prefix, as it was a matching in ngnix.
So if we hardcoded the base path `/lambdas` in the Catalyst code, but in the future we decide to expose it in another way , that would result a bug. This way, nginx exposes each service on a custom endpoint and configures the `X-Forwarded-Host` to contain the original base path.

**Comment by menduz** [comment]
Knowing "where" your microservice is to generate routes is a highway to hell. Instead we could do absolute URI for most scenarios:

## Example
```diff
function calculateNextUrl(req: Request, queryParams: string) {
-  const host = req.get('X-Forwarded-Host') ?? req.get('Host')
-  return req.protocol + '://' + host + req.baseUrl + req.path + '?' + queryParams
  return '?' + queryParams
}
```

```ts
async function fetchAll(url: string){
  const ret = []
  let result = await fetchJson(url)
  ret.push(result.records)
  while(result.next != undefined){
//    result = await fetchJson(url) // this is with absolute url
    result = await fetchJson(new URL(result.next, url)( // this is with relative urls
    ret.push(result.records)
  }
  return ret
}
```

We will never cover all the scenarios trying to recreate URLs, like the protocol, behind NGINX we have http (upstream) but for most implementations NGINX has https enabled. And that breaks the URL generation too.

**Comment by menduz** [comment]
Knowing "where" your microservice is to generate routes is a highway to hell. Instead we could do absolute URI for most scenarios:

## Example
```diff
function calculateNextUrl(req: Request, queryParams: string) {
-  const host = req.get('X-Forwarded-Host') ?? req.get('Host')
-  return req.protocol + '://' + host + req.baseUrl + req.path + '?' + queryParams
+  return '?' + queryParams
}
```

```ts
async function fetchAll(url: string){
  const ret = []
  let result = await fetchJson(url)
  ret.push(result.records)
  while(result.next != undefined){
    // this is with absolute url
    // result = await fetchJson(url) 

    // this is with relative urls, also works for absolute "new URL(path, baseUrl)"
    result = await fetchJson(new URL(result.next, url))
    ret.push(result.records)
  }
  return ret
}
```

We will never cover all the scenarios trying to recreate URLs, like the protocol, behind NGINX we have http (upstream) but for most implementations NGINX has https enabled. And that breaks the URL generation too.

**Comment by agusaldasoro** [comment]
We are changing Catalyst to use the relative path as the next link. So, this change is no longer needed.

**Pull request closed without merging**
